<template>
    <Navbar />

    <div class="comfy-reader-container">
        <h1>ComfyUI Metadata Extractor (Fixed)</h1>
        <p class="instruction">Upload a PNG generated by ComfyUI.</p>

        <div class="upload-section">
            <input type="file" accept="image/png" @change="handleFileUpload" />
        </div>

        <div v-if="imageUrl" class="preview-section">
            <img :src="imageUrl" alt="Uploaded ComfyUI Image" class="preview-image" />
        </div>

        <div v-if="metadata" class="metadata-section">
            <h2>Extracted Data</h2>

            <div class="data-block" v-if="metadata.promptDisplay">
                <h3>Positive Prompt</h3>
                <pre>{{ metadata . promptDisplay }}</pre>
            </div>

            <div class="data-block" v-if="metadata.workflowDisplay">
                <h3>Workflow Graph</h3>
                <pre>{{ metadata . workflowDisplay }}</pre>
            </div>

            <details class="data-block">
                <summary style="cursor: pointer; color: #3498db; font-weight: bold;">View Raw Metadata Keys (Debug)
                </summary>
                <pre>{{ metadata . rawKeys }}</pre>
            </details>
        </div>

        <div v-if="error" class="error-message">
            {{ error }}
        </div>
    </div>
</template>

<script setup>
    import {
        ref
    } from 'vue';
    import exifReader from 'exifreader';
    import Navbar from '@/components/Navbar.vue';

    const imageUrl = ref(null);
    const metadata = ref(null);
    const error = ref(null);

    const handleFileUpload = (event) => {
        const file = event.target.files[0];
        if (!file) return;

        // Reset state
        metadata.value = null;
        error.value = null;
        imageUrl.value = URL.createObjectURL(file);

        const reader = new FileReader();

        reader.onload = (e) => {
            const arrayBuffer = e.target.result;

            try {
                const tags = exifReader.load(arrayBuffer);

                console.log('All available tags:', tags);

                const getTagValue = (tagName) => {
                    if (!tags[tagName]) return null;
                    // exifreader usually returns { description: "value", ... }
                    return tags[tagName].description || tags[tagName];
                };

                let promptRaw = getTagValue('prompt');
                let workflowRaw = getTagValue('workflow');

                if (!promptRaw && !workflowRaw) {
                    promptRaw = getTagValue('parameters');
                }

                if (!promptRaw && !workflowRaw) {
                    const availableKeys = Object.keys(tags);
                    metadata.value = {
                        promptDisplay: null,
                        workflowDisplay: null,
                        rawKeys: availableKeys.length > 0 ? JSON.stringify(availableKeys, null, 2) :
                            "No text chunks found."
                    };
                    error.value =
                        "Standard ComfyUI keys ('prompt', 'workflow') not found. See 'View Raw Metadata Keys' below.";
                    return;
                }

                let parsedPrompt = null;
                let parsedWorkflow = null;

                if (promptRaw) {
                    try {
                        const parsed = JSON.parse(promptRaw);
                        parsedPrompt = typeof parsed === 'object' ? JSON.stringify(parsed, null, 2) : promptRaw;
                    } catch (e) {
                        parsedPrompt = promptRaw;
                    }
                }

                if (workflowRaw) {
                    try {
                        const parsed = JSON.parse(workflowRaw);
                        parsedWorkflow = JSON.stringify(parsed, null, 2);
                    } catch (e) {
                        parsedWorkflow = workflowRaw;
                    }
                }

                metadata.value = {
                    promptDisplay: parsedPrompt,
                    workflowDisplay: parsedWorkflow,
                    rawKeys: null // Hide raw keys if successful
                };

            } catch (err) {
                console.error(err);
                error.value = "Failed to parse image metadata. Ensure it is a valid PNG.";
            }
        };

        reader.onerror = () => {
            error.value = "Failed to read file.";
        };

        reader.readAsArrayBuffer(file);
    };
</script>

<style>
    .comfy-reader-container {
        max-width: 800px;
        margin: 2rem auto;
        font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
        color: #333;
    }

    h1 {
        text-align: center;
        color: #2c3e50;
    }

    .instruction {
        text-align: center;
        color: #666;
        margin-bottom: 2rem;
    }

    .upload-section {
        text-align: center;
        margin-bottom: 2rem;
    }

    .preview-image {
        max-width: 100%;
        height: auto;
        border-radius: 8px;
        box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
        display: block;
        margin: 0 auto 2rem auto;
    }

    .metadata-section {
        background: #f9f9f9;
        padding: 1.5rem;
        border-radius: 8px;
        border: 1px solid #eee;
    }

    .data-block {
        margin-bottom: 1.5rem;
    }

    .data-block h3 {
        margin-top: 0;
        font-size: 1.1rem;
        color: #2c3e50;
        border-bottom: 2px solid #3498db;
        display: inline-block;
        padding-bottom: 0.25rem;
    }

    pre {
        background: #2d2d2d;
        color: #ccc;
        padding: 1rem;
        border-radius: 4px;
        overflow-x: auto;
        font-size: 0.85rem;
        white-space: pre-wrap;
        word-wrap: break-word;
        max-height: 400px;
    }

    .error-message {
        color: #e74c3c;
        text-align: center;
        font-weight: bold;
        margin-top: 1rem;
    }

    details {
        background: #fff;
        border: 1px solid #ddd;
        padding: 0.5rem;
        border-radius: 4px;
    }
</style>
