<template>
    <Navbar />

    <div class="comfy-reader-container">

        <div class="flex flex-col md:flex-row">
            <div class="input-segment">
                <Empty v-if="!imageUrl" class="border border-dashed" >
                    <EmptyHeader>
                        <EmptyMedia variant="icon">
                            <ImagePlus />
                        </EmptyMedia>

                        <EmptyTitle>ComfyUI Prompt Reader</EmptyTitle>
                        <EmptyDescription>
                            Upload an image generated by ComfyUI to read it's prompt.
                        </EmptyDescription>
                    </EmptyHeader>
                    <EmptyContent>
                        <div class="flex flex-col gap-1">
                            <Input type="file" ref="imageInput" accept="image/png" @change="handleFileUpload">Upload Image</Input>
                            <!--
                                <span>or</span>
                                <Input v-model="imageUrl" placeholder="https://example.com/image.png..." />
                            -->
                        </div>
                    </EmptyContent>
                </Empty>
                <div class="flex flex-col" v-else>
                    <Card>
                        <img :src="imageUrl" alt="Uploaded ComfyUI Image"/>
                    </Card>
                    <div class="flex justify-end-safe mt-2">
                        <Button variant="destructive" @click="clearImage">
                            Clear Image
                        </Button>
                    </div>
                </div>
            </div>
            <div class="output-segment flex flex-1 flex-col gap-3">
                <Card class="border-green-500 border-solid border-2">
                    <CardHeader>
                        <h2 class="text-xl">Positive Prompt</h2>
                    </CardHeader>

                    <CardContent>
                        <code v-if="metadata">
                            {{ metadata . positive }}
                        </code>

                        <div class="flex flex-end">
                            <Button variant="outline" @click="() => {}">
                                <Copy class="h-4 w-4" />
                                <span>Copy</span>
                            </Button>
                        </div>
                    </CardContent>
                </Card>
                <Card class="border-red-500 border-solid border-2">
                    <CardHeader>
                        <h2 class="text-xl">Negative Prompt</h2>
                    </CardHeader>

                    <CardContent>
                        <code v-if="metadata">
                            {{ metadata . negative }}
                        </code>

                        <div class="flex flex-end">
                            <Button variant="outline" @click="() => {}">
                                <Copy class="h-4 w-4" />
                                <span>Copy</span>
                            </Button>
                        </div>
                    </CardContent>
                </Card>
            </div>
        </div>


        <div v-if="metadata" class="metadata-section">
            <div class="data-block" v-if="metadata.workflowDisplay">
                <h3>Workflow Graph</h3>
                <pre>{{ metadata . workflowDisplay }}</pre>
            </div>

            <details class="data-block">
                <summary style="cursor: pointer; color: #3498db; font-weight: bold;">View Raw Metadata Keys (Debug)
                </summary>
                <pre>{{ metadata . rawKeys }}</pre>
            </details>
        </div>

        <div v-if="error" class="error-message">
            {{ error }}
        </div>
    </div>
</template>

<script setup>
    import { ref, useTemplateRef } from 'vue';
    import Navbar from '@/components/Navbar.vue';
    import Empty from '@/components/ui/empty/Empty.vue';
    import EmptyHeader from '@/components/ui/empty/EmptyHeader.vue';
    import EmptyMedia from '@/components/ui/empty/EmptyMedia.vue';
    import EmptyTitle from '@/components/ui/empty/EmptyTitle.vue';
    import EmptyDescription from '@/components/ui/empty/EmptyDescription.vue';
    import EmptyContent from '@/components/ui/empty/EmptyContent.vue';
    import Button from '@/components/ui/button/Button.vue';
    import Card from '@/components/ui/card/Card.vue';
    import Input from '@/components/ui/input/Input.vue';
    import CardHeader from '@/components/ui/card/CardHeader.vue';
    import CardContent from '@/components/ui/card/CardContent.vue';
    import { Copy, ImagePlus } from 'lucide-vue-next';

    import exifReader from 'exifreader';

    const imageUrl = ref(null);
    const metadata = ref(null);
    const error = ref(null);

    const clearImage = (event) => {
        imageUrl.value = null;
        metadata.value = null;
        error.value = null;
    }

    const handleFileUpload = (event) => {
        const file = event.target.files[0];
        if (!file) return;

        // Reset state
        metadata.value = null;
        error.value = null;
        imageUrl.value = URL.createObjectURL(file);

        const reader = new FileReader();

        reader.onload = (e) => {
            const arrayBuffer = e.target.result;

            try {
                const tags = exifReader.load(arrayBuffer);

                console.log('All available tags:', tags);

                const getTagValue = (tagName) => {
                    if (!tags[tagName]) return null;
                    // exifreader usually returns { description: "value", ... }
                    return tags[tagName].description || tags[tagName];
                };

                let promptRaw = getTagValue('prompt');
                let workflowRaw = getTagValue('workflow');

                if (!promptRaw && !workflowRaw) {
                    promptRaw = getTagValue('parameters');
                }

                if (!promptRaw && !workflowRaw) {
                    const availableKeys = Object.keys(tags);
                    metadata.value = {
                        promptDisplay: null,
                        positive: null,
                        negative: null,
                        workflowDisplay: null,
                        rawKeys: availableKeys.length > 0 ? JSON.stringify(availableKeys, null, 2) :
                            "No text chunks found."
                    };
                    error.value =
                        "Standard ComfyUI keys ('prompt', 'workflow') not found. See 'View Raw Metadata Keys' below.";
                    return;
                }

                let parsedPrompt = null;
                let parsedWorkflow = null;

                if (promptRaw) {
                    try {
                        parsedPrompt = JSON.parse(promptRaw);
                    } catch (e) {
                        parsedPrompt = promptRaw;
                    }
                }

                if (workflowRaw) {
                    try {
                        parsedWorkflow = JSON.parse(workflowRaw);
                    } catch (e) {
                        parsedWorkflow = workflowRaw;
                    }
                }

                let positivePrompt = null;
                let negativePrompt = null;
                if (parsedPrompt) {
                    // Find the sampler
                    let sampler = null;
                    for (const [node_id, node] of Object.entries(parsedPrompt)) {
                        if (node?.class_type.indexOf('Sampler') == 0) {
                            sampler = node;
                        }
                    }

                    if (sampler) {
                        let negativeId = sampler?.inputs?.negative[0];
                        let positiveId = sampler?.inputs?.positive[0];

                        // Negative Text
                        let negativeNode = parsedPrompt[negativeId];
                        negativePrompt = negativeNode?.inputs?.['prompt'] || negativeNode?.inputs?.['text'] || '';

                        // Positive Text
                        let positiveNode = parsedPrompt[positiveId];
                        positivePrompt = positiveNode?.inputs?.['prompt'] || positiveNode?.inputs?.['text'] || '';
                    }
                }

                metadata.value = {
                    promptDisplay: typeof parsedPrompt === 'string' ? JSON.stringify(parsedPrompt, null, 2) : parsedPrompt,
                    workflowDisplay: typeof parsedWorkflow === 'string' ? JSON.stringify(parsedWorkflow, null, 2) : parsedWorkflow,
                    positive: positivePrompt,
                    negative: negativePrompt,
                    rawKeys: null // Hide raw keys if successful
                };

            } catch (err) {
                console.error(err);
                error.value = "Failed to parse image metadata. Ensure it is a valid PNG.";
            }
        };

        reader.onerror = () => {
            error.value = "Failed to read file.";
        };

        reader.readAsArrayBuffer(file);
    };
</script>

<style>
    .comfy-reader-container {
        max-width: 1024px;
        margin: 2rem auto;
    }
</style>
